###
#
# Browse Events
#
GET http://localhost:4004/odata/v4/event/Evenementen?
  # &$select=naam,datum,locatie
  # &sap-language=en

###
#
# Get Session with SessieID 1
#
GET http://localhost:4004/odata/v4/event/Sessies(1)

###
#
# Update Gebruikers with mail john.doe@example.com
#
POST http://localhost:4004/odata/v4/event/Gebruikers
Content-Type: application/json

{"mail": 101, "voornaam": "Joe"}



